### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by Mamol27** [ahungry/vader3#1]
Hi!
When I tried install your hid I've got error:
make -C hid-vader3
make: Entering directory '/home/ilys/Soft/vader3/hid-vader3'
git describe --tags --dirty >../VERSION
fatal: No names found, cannot describe anything.
make: *** [Makefile:9: ../VERSION] Error 128
rm ../VERSION
make: Leaving directory '/home/ilys/Soft/vader3/hid-vader3'

**Comment by ahungry** [comment]
Try `git fetch --tags` - it requires a local tag to build properly due to how the installation scripts work.

**Comment by Mamol27** [comment]
Thank you. It helps.
